pipeline {
    agent any

    environment {
        IMAGE_NAME = 'employee-manager-app'
        CONTAINER_NAME = 'employee-manager-container'
        APP_PORT = '8081'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
    steps {
        dir('employee-manager') {
            bat 'mvn -B clean package -DskipTests'
        }
    }
}

        stage('Build') {
    steps {
        dir('employee-manager') {
            bat 'mvn -B clean package -DskipTests'
        }
    }
}

        stage('Docker Build') {
    steps {
        dir('employee-manager') {
            bat 'docker build -t employee-manager .'
        }
    }
}

        stage('Docker Run') {
    steps {
        bat """
        docker stop employee-manager-container || exit 0
        docker rm employee-manager-container || exit 0
        docker run -d -p 8081:8081 --name employee-manager-container employee-manager
        """
    }
}
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
