pipeline {
    agent any

    environment {
        IMAGE_NAME = 'employee-manager-app'
        CONTAINER_NAME = 'employee-manager-container'
        APP_PORT = '8081'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B clean package -DskipTests'
                    } else {
                        bat 'mvn -B clean package -DskipTests'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B test'
                    } else {
                        bat 'mvn -B test'
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh "docker build -t ${IMAGE_NAME} ."
                    } else {
                        bat "docker build -t %IMAGE_NAME% ."
                    }
                }
            }
        }

        stage('Docker Run') {
    steps {
        bat """
        docker stop employee-manager-container || exit 0
        docker rm employee-manager-container || exit 0
        docker run -d -p 8081:8081 --name employee-manager-container employee-manager
        """
    }
}
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
